# Generated by Django 4.0.5 on 2022-07-24 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.IntegerField(max_length=10)),
                ('email', models.CharField(max_length=100)),
                ('role', models.BooleanField(default=False)),
            ],
        ),
    ]
