# Generated by Django 4.0.5 on 2022-07-24 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_1', '0002_alter_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.IntegerField(null=True)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
