# Generated by Django 4.0.5 on 2022-07-24 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_1', '0003_users_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_name', models.CharField(max_length=100)),
                ('descriptions', models.TextField()),
                ('company', models.CharField(max_length=100)),
                ('min_age', models.IntegerField()),
                ('max_age', models.IntegerField()),
                ('salary', models.IntegerField()),
                ('n_openings', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='users',
            new_name='user',
        ),
    ]
