# Generated by Django 4.0.5 on 2022-07-26 04:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal_1', '0005_candidates_delete_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='candidates',
            new_name='candidate',
        ),
        migrations.RenameModel(
            old_name='jobs',
            new_name='job',
        ),
    ]
