# Generated by Django 4.0.5 on 2022-08-02 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal_1', '0010_job_category_alter_job_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to='')),
                ('company_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='job',
            name='image',
        ),
        migrations.AlterField(
            model_name='job',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portal_1.company'),
        ),
    ]
