# Generated by Django 4.0.5 on 2022-08-02 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_1', '0012_alter_company_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
