# Generated by Django 4.0.5 on 2022-08-02 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_1', '0013_alter_company_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='category',
        ),
        migrations.AddField(
            model_name='job',
            name='image',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='job',
            name='company',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
