# Generated by Django 4.0.5 on 2022-08-02 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_1', '0014_remove_job_category_job_image_alter_job_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='category',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
