# Generated by Django 4.0.5 on 2022-08-03 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal_1', '0015_job_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplicant',
            name='user_id',
        ),
        migrations.AddField(
            model_name='jobapplicant',
            name='apply_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='jobapplicant',
            name='candidate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portal_1.candidate'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='image',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='jobapplicant',
            name='job_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portal_1.job'),
        ),
    ]
