# Generated by Django 4.0.5 on 2022-08-03 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_1', '0016_remove_jobapplicant_user_id_jobapplicant_apply_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplicant',
            name='company',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
