# Generated by Django 4.0.5 on 2022-08-03 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal_1', '0017_jobapplicant_company_alter_job_end_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplicant',
            old_name='job_id',
            new_name='job',
        ),
    ]
