# Generated by Django 4.0.5 on 2022-08-11 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_1', '0018_rename_job_id_jobapplicant_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplicant',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
